# Site settings
title: Kailee Zingler
email: kzingler@nmt.edu
description: Undergraduate Biology, Chemistry, and Commercialization Research Assistant
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kvzvanwhy.me" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
